
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication_UESL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Course
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Course()
    {

        this.Enrollments = new HashSet<Enrollment>();

    }


    public int ClassRecordID { get; set; }

    public string CatalogNumber { get; set; }

    public string ClassName { get; set; }

    public string Instructor { get; set; }

    public string course_Name { get; set; }

    public string classID { get; set; }

    public string MeetTime { get; set; }

    public string Location { get; set; }

    public string quarter { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Enrollment> Enrollments { get; set; }

}

}
