

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication_UESL.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DatabaseProject_UESLEntities : DbContext
{
    public DatabaseProject_UESLEntities()
        : base("name=DatabaseProject_UESLEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Enrollment> Enrollments { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }

    public virtual DbSet<courseExportKey> courseExportKeys { get; set; }

    public virtual DbSet<enrollmentExportKey> enrollmentExportKeys { get; set; }

    public virtual DbSet<studentExportKey> studentExportKeys { get; set; }

}

}

