
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication_UESL.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Student
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {

            this.Enrollments = new HashSet<Enrollment>();

        }


        public int UniqueRecordID { get; set; }

        public Nullable<int> StudentID { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string LetterGrade { get; set; }

        public string Placement { get; set; }

        public string QuarterOfPlacement { get; set; }

        public string CourseCatalogNumber { get; set; }

        public string SEVIS { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> I_20_Expiration { get; set; }

        public string gender { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DOB { get; set; }

        public string Citezenship { get; set; }

        public string School_Agent { get; set; }

        public string Agent_Email { get; set; }

        public string Transfer_ { get; set; }

        public string Telephone { get; set; }

        public string Email { get; set; }

        public string CWU_Email { get; set; }

        public string CWU_Housing { get; set; }

        public string CWU_Address { get; set; }

        public string Home_Address { get; set; }

        public string Emergency_Contact { get; set; }

        public string Emergency_Contact_Relationship { get; set; }

        public string Emergency_Contact_Phone { get; set; }

        public string Emergency_Contact_Email { get; set; }

        public string Conditional_Admission { get; set; }

        public string Status { get; set; }

        public Nullable<int> Mission_Student_ID { get; set; }

        public string Comments { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Mission_ID_Expiration { get; set; }

        public byte[] ImageContent { get; set; }

        public string ImageMimeType { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Enrollment> Enrollments { get; set; }

    }

}
